Repository Rednaxela700/CC-Project-2, pull requests merged in 2021-01, with the labels that each got.

#31 Config/#30 basic configurations
  .babelrc
  babel.config.json
  index.html
  package-lock.json
  package.json
  src/index.js
  styles/App.css
  styles/App.scss
  styles/_global.scss
  styles/base/_mixins.scss
  styles/base/_variables.scss
  test/sampleJavaScript.spec.js
  test/setupJest.js
Labels: dependencies

#42 feature/#7 Verifying if answer is correct
  src/app/logic/isAnswerCorrect.js
Labels: estimation: 2

#75 Feature/#74 extend players logic
  src/app/logic/ComputerPlayer.js
  src/app/logic/HumanPlayer.js
  src/app/logic/Player.js
Labels: enhancement

#80 Refactor #20-mode-rules
  src/app/components/ModeRules.js
Labels: estimation: 2

#81 Feature/#23 menu game modes ranking
  src/app/App.js
  src/app/components/GameModeName.js
  src/app/components/Logo.js
  src/app/components/MainMenu.js
  src/app/components/ModeMenu.js
  src/app/components/ModeRules.js
  src/app/components/PageContent.js
  src/app/components/ScoreTable.js
  src/app/components/VisualImage.js
  src/app/utils/elementFactory.js
  styles/_components.scss
  styles/components/_buttons.scss
  styles/components/_gameModeName.scss
  styles/components/_mainMenu.scss
  styles/components/_modeMenu.scss
  styles/components/_modeRules.scss
  test/gameModeName.spec.js
Labels: estimation: 13
